name: dlaw9-dist
recipe: drupal9
config:
  webroot: web
  php: '7.4'
services:
  search:
    type: solr:8
    portforward: true
    core: dlaw
    config:
      dir: web/modules/composer/search_api_solr/jump-start/solr8/config-set
